name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  unit_tests:
    name: Run .NET unit tests
    runs-on: windows-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Start Azure Cosmos DB emulator
        run: |
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          $startEmulatorCmd = "Start-CosmosDbEmulator -NoFirewall -NoUI -EnableGremlin
          Write-Host $startEmulatorCmd
          Invoke-Expression -Command $startEmulatorCmd

          Get-Item env:* | Sort-Object -Property Name
          for ($i=0; $i -lt 10; $i++) {
            $status=Get-CosmosDbEmulatorStatus 
            if ($status -ne "Running") {
              sleep 30;
              Write-Host "Cosmos DB Emulator Status: $status" -ForegroundColor yellow
            } else {
              break;
            }
          }


         
          
        
